### ISSUE TITLE
Unable to find template plugin matching graphql-codegen-hasura-gql

### ISSUE THREAD

**Issue by FDiskas** [ablestack/graphql-codegen-hasura#26]
No mater what I did - tried reinstalling and so on. I'm still getting errors like:
```
Unable to find template plugin matching graphql-codegen-hasura-typescript
```
```
Unable to find template plugin matching graphql-codegen-hasura-react
```
```
Unable to find template plugin matching graphql-codegen-hasura-client-config
```

Is this some kind of dependency naming issue?

![image](https://user-images.githubusercontent.com/468006/110217878-3f40d980-7ebf-11eb-8960-c1cab194100e.png)

**Comment by jamshally** [comment]
@FDiskas - The dependencies have updated quite a bit since last worked on this project. I just updated them, and resolved all this issues I found. Try getting latest, and seeing if this takes care of your issues.

Side note - the demo in this project relies on the schema from the Hasura hosted demos - which currently seem to be failing. I have logged an issue with the Hasura team about this (on their Discord server). Until they address this, the generate portion of the demo will not work. However, you could configure the demo to use your own schema instead, which should work. This would just require:

 - Change Schema config in this file: graphql-codegen-gql.yaml
 - Update customFragments to match entities in your own schema, in this file: customFragments

**Comment by FDiskas** [comment]
I downloaded repozitory arcive as a zip file extracted only the demo folder - navigated to it run `npm i` and `npm run generate` got the same errors
![image](https://user-images.githubusercontent.com/468006/110361858-4267d100-8049-11eb-8b94-5fff3d26ca36.png)

**Comment by FDiskas** [comment]
Reinstalled all packages - changed schema endpoint path and it works now

[aus-hasura_1615228140021.zip](https://github.com/ablestack/graphql-codegen-hasura/files/6103387/aus-hasura_1615228140021.zip)
